name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Install dependencies
        run: composer install --ansi --no-interaction --no-progress

      - name: Check code style
        run: composer lint

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Install dependencies
        run: composer install --ansi --no-interaction --no-progress

      - name: Analyse code
        run: composer analyse
  
  unit-tests:
    name: Unit tests
    needs: [ code-style, static-analysis ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug

      - name: Install dependencies
        run: composer install --ansi --no-interaction --no-progress

      - name: Run tests with coverage
        run: composer test:coverage:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
